Move Same Origin Policy to Goals; add example in Applications section.
krgovind/first-party-sets pull request #1
Opened 2021-07-26 14:43 UTC by cfredric

This PR moves the mention of the Same Origin Policy from non-goals to goals, since it is our goal to preserve/respect the SOP. It also augments the Applications section with an example, including a graphic and a brief walkthrough.

2021-08-10 14:11 UTC, krgovind requested changes

2021-08-10 14:11 UTC, krgovind commented on README.md
> +The first page, case *a*, is hosted on a third-party domain (https://other.example) and embeds an iframe from https://member1.example. We say that this iframe is in a *cross-party context*, since the
Could you format all URLs with backticks, in keeping with the general style?

2021-08-10 14:11 UTC, krgovind commented on README.md
> +The first page, case *a*, is hosted on a third-party domain (https://other.example) and embeds an iframe from https://member1.example. We say that this iframe is in a *cross-party context*, since the
Start with "On browsers where cross-site tracking protections are enabled, the first page..."

2021-08-10 14:11 UTC, krgovind commented on README.md
> +![Cross-party and same-party embeddings](images/party_embeddings.png)
The cross-mark and check-mark by themselves are a bit ambiguous. Could you add a note next to them? e.g. in case a, you can say "No cookies sent"; and in case b, you can say "SameParty cookies sent".

2021-08-10 14:11 UTC, krgovind commented on README.md
>  -   An iframe’s access to its own storage should be allowed when embedded on a site within the same first-party set. For example, this would allow a `https://b.example` iframe within `https://a.examp
Based on recent discussions, due to the presence of side-channels when granted access to storage in cross-site, same-party contexts; we may also need to consider a future "opt-in" to allow this type of cross-site, same-party access to storage. Could you remove this bullet? I think we should add another section on why Storage (in a separate PR) and Storage Partitioning can't use FPS (without a developer opt-in)

2021-08-10 14:11 UTC, krgovind commented on README.md
> +The first page, case *a*, is hosted on a third-party domain (https://other.example) and embeds an iframe from https://member1.example. We say that this iframe is in a *cross-party context*, since the
Could you remove mention of "storage" everywhere; since as per recent discussions, we only want SameParty cookies to interact with FPS?

2021-08-11 14:21 UTC, cfredric commented on README.md
> +![Cross-party and same-party embeddings](images/party_embeddings.png)
Done. I also added some prose to spell this out more explicitly.

2021-08-11 14:21 UTC, cfredric commented on README.md
> +The first page, case *a*, is hosted on a third-party domain (https://other.example) and embeds an iframe from https://member1.example. We say that this iframe is in a *cross-party context*, since the
Done.

2021-08-11 14:21 UTC, cfredric commented on README.md
>  -   An iframe’s access to its own storage should be allowed when embedded on a site within the same first-party set. For example, this would allow a `https://b.example` iframe within `https://a.examp
Done.

2021-08-30 22:38 UTC, krgovind commented
Thanks Chris! (my apologies for the late response on this)

2021-08-30 22:41 UTC, merged